name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t himanshhhh/eventa-backend:latest .

      - name: Push Image to Docker Hub
        run: docker push himanshhhh/eventa-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull himanshhhh/eventa-backend:latest

      - name: Delete Old Container
        run: docker rm -f eventa-backend-container || true

      - name: Run Docker Container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name eventa-backend-container \
            --restart unless-stopped \
            -e PORT='${{ secrets.PORT }}' \
            -e MongoDB_URI='${{ secrets.MONGO_URI }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            -e JWT_EXPIRY='${{ secrets.JWT_EXPIRY }}' \
            -e EMAIL_USER='${{ secrets.EMAIL_USER }}' \
            -e EMAIL_PASS='${{ secrets.EMAIL_PASS }}' \
            -e TWILIO_ACCOUNT_SID='${{ secrets.TWILIO_ACCOUNT_SID }}' \
            -e TWILIO_AUTH_TOKEN='${{ secrets.TWILIO_AUTH_TOKEN }}' \
            -e TWILIO_PHONE_NUMBER='${{ secrets.TWILIO_PHONE_NUMBER }}' \
            -e KHALTI_SECRET_KEY='${{ secrets.KHALTI_SECRET_KEY }}' \
            -e ESEWA_SECRET_KEY='${{ secrets.ESEWA_SECRET_KEY }}' \
            -e GEMINI_API_KEY='${{ secrets.GEMINI_API_KEY }}' \
            himanshhhh/eventa-backend:latest